# Generated by Django 6.0.3 on 2026-06-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default='Ghana', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[('GHS', 'Ghana Cedi'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira')], default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], default='paid', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
