# Generated by Django 6.0.3 on 2026-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('organizer', 'Organizer'), ('doorstaff', 'Door Staff'), ('super_admin', 'Super Admin')], default='attendee', max_length=20),
        ),
    ]
