# Generated by Django 6.0.3 on 2026-03-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='nft_token_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nft_token_uri',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nft_tx_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner_wallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
