# Generated by Django 6.0.3 on 2026-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_nft_token_id_ticket_nft_token_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_data',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('transferred', 'Transferred'), ('refunded', 'Refunded'), ('resale', 'Resale')], default='active', max_length=20),
        ),
    ]
