# Generated by Django 6.0.3 on 2026-06-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_nft_mint_failed_ticket_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorstaffcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
