# Generated by Django 6.0.3 on 2026-06-13 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_country_event_currency_event_event_type_and_more'),
        ('tickets', '0006_doorstaffcode_used_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf_redemption_used',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_id', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('qr_data', models.CharField(blank=True, max_length=500, unique=True)),
                ('qr_image', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf_redemption_used', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'db_table': 'registrations',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'attendee')},
            },
        ),
    ]
