# Generated by Django 6.0.3 on 2026-08-04 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_tickettier'),
        ('tickets', '0007_ticket_pdf_redemption_used_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.tickettier'),
        ),
    ]
